[book]
authors = ["Ray Miles, Lachlan Shoesmith, Khye Jac Low, Dylan Huynh, Nicole Chun, Jeremy Le, Alex Lee"]
language = "en"
src = "src"
title = "DevSoc Training Program Exercises"

[output.html]
site-url = "/book/"